<?php

// Standalone design prototypes: pack existing mascot layers and Laravel dictionaries.
$root = dirname(__DIR__);
$directory = $root.'/public/plummo';
$catalog = json_decode(file_get_contents($directory.'/catalog.json'), true, flags: JSON_THROW_ON_ERROR);
$files = ['base' => 'base.svg'];
foreach ($catalog['accessories'] as $item) {
    $files[$item['id']] = $item['front'];
    if (isset($item['back'])) {
        $files[$item['id'].'-back'] = $item['back'];
    }
}
$parts = [];
foreach ($files as $id => $file) {
    $body = preg_replace('/^<svg[^>]*>|<\/svg>\s*$/', '', file_get_contents($directory.'/'.$file));
    $parts[$id] = preg_replace('/<title>.*?<\/title>/', '', $body);
}
$messages = [];
foreach (['fr', 'en'] as $locale) {
    $messages[$locale] = require $root.'/lang/'.$locale.'/maquettes.php';
}
$data = compact('catalog', 'parts', 'messages');
file_put_contents($root.'/public/maquettes/data.js', "// Generated by scripts/build-html-mockups.php.\nwindow.PLUMMO_MOCK_DATA = ".json_encode($data, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_THROW_ON_ERROR).";\n");
echo "Mockup dictionaries and original SVG layers packed.\n";
